version: '1.0'
volumes:
  data:

services:
# OpenVPN CLient
  openvpn:
    container_name: openvpn-client
    image: domoniquesmarthome/openvpn-client
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - type: volume
        source: data
        target: /config
        volume:
          subpath: openvpn
    network_mode: host
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m

# Portainer Edge Agent
  portainer_agent:
    container_name: portainer-agent
    image: portainer/agent:2.19.4
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          subpath: agent
    network_mode: host
    environment:
      - EDGE=1
      - EDGE_INSECURE_POLL=1
      - EDGE_ID=${EDGE_ID}
      - EDGE_KEY=${EDGE_KEY}
