# version: '2.0'
networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.100.0.0/16
         gateway: 172.100.0.1

services:
# MQTT Server
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_FOLDER}/mosquitto/config:/mosquitto/config
      - ${ROOT_FOLDER}/mosquitto/data:/mosquitto/data
      - ${ROOT_FOLDER}/mosquitto/log:/mosquitto/log
    networks:
      - default
    ports:
      - 1883:1883
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m

# Zigbee2MQTT Server
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.1.3
    restart: unless-stopped
    depends_on:
      - mqtt
    environment:
      - TZ=${TZ}
    devices:
      - ${ZIGBEE_DEVICE}:/dev/ttyACM0
    volumes:
      - /${ROOT_FOLDER}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    networks:
      - default
    ports:
      - 8081:8080
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m

# Domoticz Server
  domoticz:
    container_name: domoticz
    image: domoticz/domoticz:2024.7
    restart: unless-stopped
    depends_on:
      - zigbee2mqtt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WWW_PORT=80
    devices:
      - ${DOMOTICZ_ACM0_DEVICE}:/dev/ttyACM0
      - ${DOMOTICZ_ACM1_DEVICE}:/dev/ttyACM1
    volumes:
      - ${ROOT_FOLDER}/domoticz:/opt/domoticz/userdata
      - /sys:/sys
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 6144:6144
      - 1443:1443

# Homebride Server
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    depends_on:
      - domoticz
    volumes:
      - ${ROOT_FOLDER}/homebridge:/homebridge
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 10m

# Opensprinkler Server
  ospi:
    image: domoniquesmarthome/opensprinkler
    container_name: opensprinkler
    restart: none
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - TZ=${TZ}
      - ${ROOT_FOLDER}/opensprinkler/data:/data
    networks:
      - default
    ports:
      - 8083:8080
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m
