# Version: 1.0

services:
  ospi:
    image: domoniquesmarthome/opensprinkler
    container_name: opensprinkler
    restart: none
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - ${ROOT_FOLDER}/opensprinkler/data:/data
    network_mode: bridge
    ports:
      - 8080:80
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m
