services:
 domoticz:
    container_name: domoticz
    image: domoticz/domoticz
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WWW_PORT=80
    devices:
      - /dev/null:/dev/ttyACM0
      - /dev/null:/dev/ttyACM1
    volumes:
      - ./:/opt/domoticz/userdata
      - /sys:/sys
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 6144:6144
      - 1443:1443
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m
