services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    devices:
      - /dev/null:/dev/ttyACM0
    volumes:
      - ./:/app/data
      - /run/udev:/run/udev:ro
    network_mode: bridge
    ports:
      - 8080:8080
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m
